### ISSUE TITLE
Artifacts have no substats with 0.4.0

### ISSUE THREAD

**Issue by Gol-D-Ace** [xenesty/AkashaScanner#12]
Scanned Artifacts with 0.4.0 and they have no stats.

Open Akasha Scanner
Click on Artifact Scanner
Update Artifacts and Characters
Set options to Traveler Name / Minimum Level 0 / Minimum Rarity 4
Open Game at a resolution of 1920x1080
Click Start button
Wait for Scanning
In Akasha Scanner click on GOOD format export
Click on the latest entry for artifacts scanning and click export
Save file
Import to something like Genshin Optimizer
Notice that all artifacts changed and the substats are gone

**Expected behavior**
The substats aren't missing.

https://puu.sh/JxQ6q.json < json of the scan

[akashascanner-20230128215000-20230128.txt](https://github.com/xenesty/AkashaScanner/files/10528292/akashascanner-20230128215000-20230128.txt)

**Comment by PolomoPT** [comment]
Same thing happening to me. Substats aren't completely missing, just most read as flat atk/hp and +20 artifacts are only captured as having 1 or 2 substats.

**Comment by skzidan** [comment]
+20 crit rate artifact showing HP% main stat in akasha lol

**Comment by xenesty** [comment]
Sorry about that. Was trying for an experimental change and it worked well for me. Will fix this asap.

**Comment by Gol-D-Ace** [comment]
No worries there. I have alternatives.
If I can provide anything for debugging let me know.
