### ISSUE TITLE
First Artifacts export in GOOD format is always empty 

### ISSUE THREAD

**Issue by Gol-D-Ace** [xenesty/AkashaScanner#15]
**Describe the bug**
Scanning for Artifacts and then saving the data as GOOD format json results in empty file.

**To Reproduce**
Scan for Artifacts
Export as GOOD format json
File is empty 

**Expected behavior**
The first export not to be an empty file.
Exporting again results in a proper file.

**Comment by xenesty** [comment]
I can't reproduce this issue. Is it like completely empty or is there any text in the export file?

**Comment by Gol-D-Ace** [comment]
Currently can't reproduce this either.
Perhaps the UI was representing a state that wasn't actually happening.

Will let you know if it happens again and ideally upload the files so you can reproduce the condition.
