### ISSUE TITLE
GOOD Format not working for me

### ISSUE THREAD

**Issue by SkylerHaataja** [xenesty/AkashaScanner#17]
**Describe the bug**
The format that sites that use GOOD format expect an entirely different formatted JSON
These are the results of clicking the Export button:
![Screenshot 2023-03-31 103355](https://user-images.githubusercontent.com/79336148/229190295-a7eaeda1-96af-4580-813f-28cf0ff908e3.png)
and none of them can be parsed by GenshinOptimizer. There is supposed to be a GOOD file generated when clicking the Export button but just those 3 files are there in the Scanned Data folder, both this latest version and the previous versions result in this issue I'm having. Any help is appreciated

**Comment by xenesty** [comment]
These files are not supposed to be in GOOD format. You need to use the "GOOD Export" function in the scanner to export to GenshinOptimiser.

**Comment by Eiion** [comment]
> You need to use the "GOOD Export" function in the scanner to export to GenshinOptimiser.

The Export feature doesn't work on any of the three tabs. Neither does Select File (to import a file exported on one of the websites) open the select file window. (See my bug report https://github.com/xenesty/AkashaScanner/issues/30)

**Comment by mkiuur** [comment]
Experiencing similar issue - Can't select Export artifacts/weapons/characters buttons and Export button greyed out. 
![image](https://github.com/xenesty/AkashaScanner/assets/31939987/a5930cea-ae36-474b-8154-2dbab96cb8e4)
