### ISSUE TITLE
Error 0x80070002

### ISSUE THREAD

**Issue by Varinets** [xenesty/AkashaScanner#5]
Don`t work for me at all. Downloaded the latest version of the Akasha Scanner, extracted archive, launched AkashaScanner.exe. It asked for Administrator permissions, I click "Yes" and error appears immediately. It says this: *screenshot*, in the details - *Details txt file*. Tried WinRAR and 7-Zip to extract archive, the same error. Visual C++ Redistributable also up to date
![image](https://user-images.githubusercontent.com/81707145/208883319-db9a53bc-0a83-46b9-8982-c53387aa771d.png)
[Details.txt](https://github.com/xenesty/AkashaScanner/files/10276837/Details.txt)

**Comment by xenesty** [comment]
Are you running any antivirus software? If yes, did it trigger any warnings when extracting the archive?

If your answer is no, then I suspect that maybe certain Windows features are missing from your computer. Can you try installing [Microsoft Edge WebView2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) on your computer? Sorry for the trouble.

**Comment by Varinets** [comment]
> Are you running any antivirus software? If yes, did it trigger any warnings when extracting the archive?
> 
> If your answer is no, then I suspect that maybe certain Windows features are missing from your computer. Can you try installing [Microsoft Edge WebView2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) on your computer? Sorry for the trouble.

Yes, I use antivirus, but I tried turning it off. It didn't help.
Installed WebView2 and everything worked. Thanks for quick help.
