### ISSUE TITLE
Achievement Scanner only scanning handful, not full page

### ISSUE THREAD

**Issue by SirKanye** [xenesty/AkashaScanner#8]
**Describe the bug**
Achievement Scanner only scanning 5 achievements. Under use existing scan record: 2023-01-08, 20:47 (5 items).
When uploade to Paimon.Moe , there are only 5 out of the 857 achievements accounted for when it scans through my 653 Achievements.

**To Reproduce**
Followed each step/action shown in Achievement Scanner Demonstration video to do
1. Opened Akasha Scanner
2. As in video, ticked the stars on Explorer, Let the Wind Lead, Their Wishes etc.
3. In-game, had the achievements screen open with the Search Bar and side-bar list of the different categories
4. After it goes through the list, left with only 5 items scanned

Attempted four times total: Three times on Latest Akasha version, twice on previous version (v0.2.1).

**Expected behavior**
Expected it to automatically scan through all 653 achievements and when uploaded to Paimon.Moe and see what ones I've got left to get.

**Screenshots**
![Achievement Scanner Screen with Records](https://user-images.githubusercontent.com/40158446/211190981-b99a4179-4bc6-4185-94e8-4cf48718668f.jpg)
![Achievement Count and Screen](https://user-images.githubusercontent.com/40158446/211190982-7a52d132-a695-4c66-87e4-904712d2e234.jpg)

**Comment by xenesty** [comment]
Thanks for reporting the issue. Can you please go to the achievement list page, search for any achievement that you have at least one star, and upload a screenshot here? Thanks a lot.

**Comment by SirKanye** [comment]
> 
After uninstalling & reinstalling VC++ as well as Akasha Scanner it seems to have finally worked. Faults on my own end as a user with my setup. Apologies for wasting any of your time, thank you for creating a wonderful and very helpful tool.
