### ISSUE TITLE
Support for seelie.me

### ISSUE THREAD

**Issue by Gol-D-Ace** [xenesty/AkashaScanner#9]
Hello.
First up great work. Was looking for an achievement scanner and finally found one that worked perfectly.

While I personally use paimon.moe for achievements there are also other sites like seelie.me that support achievements.

Seelie.me is also offering an data import/export feature which should allow you to add the data like with paimon.moe

**Comment by xenesty** [comment]
Will add this soon. Thanks for the suggestion!
